# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          always-auth: true
      - name: Install Dependencies
        run: yarn install
      - name: Build Package
        run: yarn build
      - name: Get Tag Name
        id: get_tag
        run: echo "::set-output name=tag_name::$(echo $GITHUB_REF | sed 's|refs/tags/||' | sed 's/^v//')"
      - name: Publish Package
        run: yarn pub ${{ steps.get_tag.outputs.tag_name }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
